### ISSUE TITLE
Could you please deploy the ui toolkit on cdn

### ISSUE THREAD

**Issue by Max-ChenFei** [jupyterlab-contrib/jupyter-ui-toolkit#44]
Nice work, thanks a lot.

Could you please deploy this ui toolkit on CDN, so that we can directly use it in HTML?

**Comment by fcollonval** [comment]
Thanks for you interest @Max-ChenFei 

Did you try using [unpkg](https://unpkg.com/): https://unpkg.com/@jupyter-notebook/web-components

More specifically for this version: 

```
https://unpkg.com/@jupyter-notebook/web-components@0.9.1/dist/toolkit.min.js
```

**Comment by Max-ChenFei** [comment]
Thanks, Frédéric, It works now.

The project name is `jupyter-ui-toolkit`. When I search it and found nothing, this is reason I open this issue.
I see the `link` provided by you and also search `jupyter-notebook/web-components` now I can find it on `jsdelivr`.

Will you keep the name consistent or add the note in ReadMe?

If you think it is fine, please close the issue.

**Comment by fcollonval** [comment]
Thanks @Max-ChenFei 

Would you be willing to propose a PR to update the README? You can do that directly from GitHub. There should be a pencil icon on the top right of the file on that page:

https://github.com/jupyterlab-contrib/jupyter-ui-toolkit/blob/main/README.md

**Comment by Max-ChenFei** [comment]
I will do it.
