### ISSUE TITLE
Should `@microsoft/fast-components` be vendored in this repo?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyter-ui-toolkit#85]
> If so, is there a long-term plan that would not require to vendor `@microsoft/fast-components` in this repo?

And for this question?

Asking to get a better idea of the implications, and what that would mean in terms of maintenance work for maintainers in case this proposal is accepted: https://github.com/jupyterlab/team-compass/issues/227

_Originally posted by @jtpio in https://github.com/jupyterlab-contrib/jupyter-ui-toolkit/issues/80#issuecomment-1875679844_

**Comment by jtpio** [comment]
Opening a new issue for visibility, as the comment above was originally posted on an already merged PR.

**Comment by jtpio** [comment]
There was some discussions about this during the previous JupyterLab call: https://github.com/jupyterlab/team-compass/issues/229#issuecomment-1885396136

@fcollonval would you mind providing some information about this here in this issue, so it's easier to find and track in the future? Thanks!

**Comment by fcollonval** [comment]
The fast library decided to focus on providing the tooling to create an adaptive and accessible components library; not the library itself. Therefore they deprecated the package `@microsoft/fast-components`. And it will be removed in the next major release. In the meantime the community started an substitute: https://github.com/Adaptive-Web-Community/Adaptive-Web-Components. But it is based on the prerelease of the next major iteration of Fast system. Therefore it was decided to import in this project the piece of `@microsoft/fast-components` (mainly the styling of them).
